package error

import (
	"testing"
)

func TestError(t *testing.T){
	ContextBack()
}
